# Canonical skill taxonomy and aliases for IT job skills
# Each skill can have multiple aliases (common alternate spellings, abbreviations, etc.)

SKILL_TAXONOMY = [
    {"skill": "Python", "aliases": ["python3", "py"]},
    {"skill": "Java", "aliases": []},
    {"skill": "JavaScript", "aliases": ["js", "node.js", "nodejs"]},
    {"skill": "SQL", "aliases": ["postgresql", "mysql", "sqlite", "tsql", "pl/sql"]},
    {"skill": "AWS", "aliases": ["amazon web services", "ec2", "s3", "lambda"]},
    {"skill": "Azure", "aliases": ["microsoft azure"]},
    {"skill": "GCP", "aliases": ["google cloud", "google cloud platform"]},
    {"skill": "Docker", "aliases": []},
    {"skill": "Kubernetes", "aliases": ["k8s"]},
    {"skill": "Linux", "aliases": ["ubuntu", "redhat", "centos"]},
    {"skill": "Git", "aliases": ["github", "gitlab"]},
    {"skill": "C++", "aliases": ["cpp"]},
    {"skill": "C#", "aliases": ["csharp"]},
    {"skill": "HTML", "aliases": []},
    {"skill": "CSS", "aliases": []},
    {"skill": "React", "aliases": ["react.js", "reactjs"]},
    {"skill": "Angular", "aliases": ["angular.js", "angularjs"]},
    {"skill": "Vue.js", "aliases": ["vuejs", "vue"]},
    {"skill": "TypeScript", "aliases": ["ts"]},
    {"skill": "NoSQL", "aliases": ["mongodb", "cassandra", "dynamodb"]},
    {"skill": "Machine Learning", "aliases": ["ml", "scikit-learn", "tensorflow", "pytorch"]},
    {"skill": "Data Science", "aliases": ["data scientist"]},
    {"skill": "DevOps", "aliases": []},
    {"skill": "Agile", "aliases": ["scrum", "kanban"]},
    {"skill": "Jenkins", "aliases": []},
    {"skill": "CI/CD", "aliases": ["continuous integration", "continuous delivery"]},
    {"skill": "REST API", "aliases": ["restful api"]},
    {"skill": "GraphQL", "aliases": []},
    {"skill": "Tableau", "aliases": []},
    {"skill": "Power BI", "aliases": ["powerbi"]},
    {"skill": "Snowflake", "aliases": []},
    {"skill": "Airflow", "aliases": []},
    {"skill": "Spark", "aliases": ["apache spark"]},
    {"skill": "Hadoop", "aliases": []},
    {"skill": "Scala", "aliases": []},
    {"skill": "R", "aliases": []},
    {"skill": "SAS", "aliases": []},
    {"skill": "ETL", "aliases": ["extract transform load"]},
    {"skill": "Business Intelligence", "aliases": ["bi"]},
    {"skill": "Excel", "aliases": ["microsoft excel"]},
    {"skill": "Shell Scripting", "aliases": ["bash", "sh", "zsh"]},
    {"skill": "PHP", "aliases": []},
    {"skill": "Ruby", "aliases": ["ruby on rails"]},
    {"skill": "Go", "aliases": ["golang"]},
    {"skill": "Perl", "aliases": []},
    {"skill": "C", "aliases": []},
    {"skill": "Objective-C", "aliases": ["objective c"]},
    {"skill": "Swift", "aliases": []},
    {"skill": "Android", "aliases": ["android development"]},
    {"skill": "iOS", "aliases": ["ios development"]},
    {"skill": "Unity", "aliases": []},
    {"skill": "Unreal Engine", "aliases": []},
    {"skill": "Salesforce", "aliases": []},
    {"skill": "SAP", "aliases": []},
    {"skill": "Oracle", "aliases": []},
    {"skill": "Jira", "aliases": []},
    {"skill": "Confluence", "aliases": []},
    {"skill": "Figma", "aliases": []},
    {"skill": "Adobe Photoshop", "aliases": ["photoshop"]},
    {"skill": "Adobe Illustrator", "aliases": ["illustrator"]},
    {"skill": "AWS Lambda", "aliases": []},
    {"skill": "Terraform", "aliases": []},
    {"skill": "Ansible", "aliases": []},
    {"skill": "Puppet", "aliases": []},
    {"skill": "Chef", "aliases": []},
    {"skill": "Linux Administration", "aliases": []},
    {"skill": "Network Security", "aliases": []},
    {"skill": "Penetration Testing", "aliases": ["pentesting"]},
    {"skill": "Blockchain", "aliases": []},
    {"skill": "IoT", "aliases": ["internet of things"]},
    {"skill": "Big Data", "aliases": []},
    {"skill": "Cloud Computing", "aliases": []},
    {"skill": "Microservices", "aliases": []},
    {"skill": "Spring", "aliases": ["spring boot"]},
    {"skill": "Django", "aliases": []},
    {"skill": "Flask", "aliases": []},
    {"skill": "FastAPI", "aliases": []},
    {"skill": "REST", "aliases": []},
    {"skill": "SOAP", "aliases": []},
    {"skill": "Redux", "aliases": []},
    {"skill": "Bootstrap", "aliases": []},
    {"skill": "SASS", "aliases": []},
    {"skill": "LESS", "aliases": []},
    {"skill": "Webpack", "aliases": []},
    {"skill": "Gulp", "aliases": []},
    {"skill": "Grunt", "aliases": []},
    {"skill": "Jest", "aliases": []},
    {"skill": "Mocha", "aliases": []},
    {"skill": "Chai", "aliases": []},
    {"skill": "Jupyter", "aliases": ["jupyter notebook"]},
    {"skill": "Matplotlib", "aliases": []},
    {"skill": "Seaborn", "aliases": []},
    {"skill": "Plotly", "aliases": []},
    {"skill": "Looker", "aliases": []},
    {"skill": "Qlik", "aliases": []},
    {"skill": "PowerShell", "aliases": []},
    {"skill": "VBA", "aliases": []},
    {"skill": "Unity3D", "aliases": []},
    {"skill": "Game Development", "aliases": []},
    {"skill": "Testing", "aliases": ["unit testing", "integration testing"]},
    {"skill": "Automation", "aliases": []},
    {"skill": "Scrum", "aliases": []},
    {"skill": "Kanban", "aliases": []},
    {"skill": "Product Management", "aliases": []},
    {"skill": "Project Management", "aliases": []},
    {"skill": "Business Analysis", "aliases": []},
    {"skill": "Technical Writing", "aliases": []},
    {"skill": "Support", "aliases": ["technical support"]},
]

# Helper: build alias-to-canonical mapping for fast lookup
ALIAS_TO_SKILL = {}
for entry in SKILL_TAXONOMY:
    ALIAS_TO_SKILL[entry["skill"].lower()] = entry["skill"]
    for alias in entry["aliases"]:
        ALIAS_TO_SKILL[alias.lower()] = entry["skill"]

def extract_skills(text):
    """
    Extract canonical skills from a text string using the taxonomy and aliases.
    Returns a set of canonical skill names.
    """
    found = set()
    text_lower = text.lower()
    for alias, skill in ALIAS_TO_SKILL.items():
        if alias in text_lower:
            found.add(skill)
    return found
